//import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";

//const geistSans = Geist({
  //variable: "--font-geist-sans",
  //subsets: ["latin"],
//});

//const geistMono = Geist_Mono({
  //variable: "--font-geist-mono",
  //subsets: ["latin"],
//});

//export const metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
//};

//export default function RootLayout({ children }) {
  //return (
    //<html lang="en">
      //<body
        //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      //>
        //{children}
      //</body>
    //</html>
  //);
//}

//new
// File: app/layout.js
// We wrap our entire application with the AuthProvider here.

import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext"; // Import the provider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wearable Monitor",
  description: "Live Operation Monitor",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider> {/* Wrap everything */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
